influxdb:
  image:
    repository: influxdb
    tag: 1.7-alpine
  replicas: 1
  port: 8086

telegraf:
  image:
    repository: telegraf
    tag: 1.9-alpine
  replicas: 1
  port: 8125

chronograf:
  image:
    repository: chronograf
    tag: 1.7-alpine
  replicas: 1
  port: 8888

kapacitor:
  image:
    repository: kapacitor
    tag: 1.5-alpine
  replicas: 1
  port: 9092

ui:
  enabled: true

ingress:
  host: localhost
  path: /
  network: traefik
